### ISSUE TITLE
UDN: Problem Tracker for Surya

### ISSUE THREAD

**Issue by tssurya** [ovn-kubernetes/ovn-kubernetes#4720]
### What is this issue about?

- [ ] E0911 12:32:31.821753    1932 obj_retry.go:733] Failed to delete *factory.endpointSliceForGateway udn-services-6091/udn-service-h8r28, error: failed to get active network config for network 4zggv_tenant-red

- [ ] E0911 12:32:31.776714    1932 route_manager.go:176] Route Manager: failed to restore route because unable to get link by index 19: Link not found

- [ ] E0911 11:35:03.537154    1932 obj_retry.go:533] Failed to create *factory.serviceForGateway udn-services-6091/udn-service, error: AddService failed for nodePortWatcher: failed to get active network config for network 4zggv_tenant-red

**Comment by tssurya** [comment]
- [ ] I see errors like:
```
surya@fedora:~/go/src/github.com/ovn-org/ovn-kubernetes/go-controller$ oc logs -n ovn-kubernetes ovnkube-node-xrb6k ovn-northd | grep "No path for static"
2024-09-11T09:15:39.002Z|00013|northd|WARN|No path for static route 10.128.0.0/24; next hop 100.88.0.2
2024-09-12T18:41:19.356Z|00017|northd|WARN|No path for routing policy priority 1004; next hop 10.128.0.2
```
and
```
2024-09-11T09:15:39.003Z|00013|northd|WARN|No path for static route 2014:100:200:1::/64; next hop fd97::3
```
etc happening.
